FROM maven:3.8.4-openjdk-17-slim

WORKDIR /app

COPY pom.xml .

RUN mvn dependency:go-offline

RUN mvn -version

COPY src/ /app/src/

RUN mvn package

EXPOSE 8080

CMD ["java", "-jar", "target/api.com-0.0.1-SNAPSHOT.jar"]